# å·²é…ç½®å¹¶å¯åŠ¨ Nikki ç­–ç•¥ç»„
# å¼€å§‹é…ç½®è§„åˆ™å’Œè§„åˆ™é›†

#############################################
# è®¢é˜…å®šä¹‰ *æ— é¡»å…³æ³¨* 
#############################################

proxy-providers:
  SSRDOG:
    url: "https://83c3d83ea347878b7d2c20008d870bfd.beijing-aliyuncs.sbs/s?t=83c3d83ea347878b7d2c20008d870bfd.jpg" # <--- è¯·åœ¨æ­¤å¡«å…¥æœºåœºAçš„è®¢é˜…é“¾æ¥
    type: http
    interval: 86400
    health-check: {enable: true, url: "https://cp.cloudflare.com/generate_204", interval: 300, timeout: 3000}
    override:
      additional-prefix: "[SSRDOG]"

  CroLAX:
    url: "https://2000w.xyz/c/pyupr6wbs9ge9bs4" # <--- è¯·åœ¨æ­¤å¡«å…¥æœºåœºBçš„è®¢é˜…é“¾æ¥
    type: http
    interval: 86400
    health-check: {enable: true, url: "https://cp.cloudflare.com/generate_204", interval: 300, timeout: 3000}
    override:
      additional-prefix: "[CroLAX]"
proxies:
  - {name: "ç›´è¿", type: direct, udp: true}
  - {name: "æ‹’ç»", type: reject}

#############################################
# åŸºç¡€å‚æ•° *æ— é¡»å…³æ³¨*
#############################################
# ä¸»è¦ç«¯å£
mixed-port: 10801
port: 7890
socks-port: 7891
redir-port: 7892
tproxy-port: 7893

allow-lan: true
mode: rule
log-level: warning
ipv6: false
unified-delay: true # ç»Ÿä¸€å»¶è¿Ÿ
tcp-concurrent: true
bind-address: '*'
find-process-mode: off # strict
global-client-fingerprint: chrome
profile:
  store-selected: true
  tracing: false
  store-fake-ip: true

# Zashboard ç½‘é¡µç®¡ç†
external-controller: '[::]:9090'
external-ui: ui
external-ui-name: Zashboard
external-ui-url: https://gh-proxy.com/https://github.com/Zephyruso/zashboard/releases/latest/download/dist-cdn-fonts.zip
secret: "181818"

# ç¡¬ä»¶ä¸æ§åˆ¶é€‰é¡¹ (ä¿æŒåŸç‰ˆé…ç½®)
interface-name: eth0
disable-keep-alive: false
keep-alive-idle: 600
keep-alive-interval: 30

# GeoIP æ•°æ®åº“ (ç”¨äº GeoIP è§„åˆ™) qWen æä¾›çš„
hosts:
  localhost.localhost: 127.0.0.1
geodata-mode: false
geodata-loader: standard
geox-url:
  geoip: "https://gh-proxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat"
  geosite: "https://gh-proxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://gh-proxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb"
  asn: "https://gh-proxy.com/https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb"
geo-auto-update: true
geo-update-interval: 72

#############################################
# å—…æ¢ *æ— é¡»å…³æ³¨*
#############################################

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  sniff:
    HTTP:
      port:
        - "80"
        - "8080"
      override-destination: true
    TLS:
      port:
        - "443"
        - "8443"
      override-destination: true
    QUIC:
      port:
        - "443"
        - "8443"
      override-destination: true
  # # å¼ºåˆ¶è§£æåŸŸå # GeminiåŠ çš„ï¼Œæˆ‘æ²¡çœ‹æ‡‚
  # force-domain: 
  #   - "+.google.com"
  # skip-domain: # è·³è¿‡åŸŸå
  #   - "Mijia Cloud"
  #   - "+.push.apple.com"

#############################################
# å…¥ç«™ *æ— é¡»å…³æ³¨*
#############################################

tun:
  enable: true
  # ä½¿ç”¨ Nikki æ··å…¥å…¨éƒ¨ä¸ä¿®æ”¹çš„æƒ…å†µï¼Œå¼€å¯æ¥å£æŒ‡å®šä¸ºnikki
  device: nikki # utun # openclash ç”¨ gvisor
  stack: system # gvisor # ä¸ç©æ¸¸æˆç”¨ system æ›´ç¨³å¦¥ï¼Œopenclash ç”¨ gvisor
  mtu: 9000 #
  gso: true #
  gso-max-size: 65536 #
  # endpoint-independent-nat: true # å¯ç”¨ç‹¬ç«‹äºç«¯ç‚¹çš„ NAT # å®‰æ ¼è§†ç•Œè®¾ç½®å¼€å¯
  # auto-route: false # é…ç½®è·¯ç”±è¡¨ # å®‰æ ¼è§†ç•Œè®¾ç½®å…³é—­
  # ä½¿ç”¨ä»…å†…æ ¸æ”¹ä¸‹é¢ä¸‰é¡¹ä¸º true # Gemini å»ºè®®å¼€å¯ä¸‹é¢ä¸‰é¡¹
  auto-route: false
  auto-redirect: false
  auto-detect-interface: false
  # åŠ«æŒDNSè¯·æ±‚
  # dns-hijack: 
  #   - "any:53"
  #   - "tcp://any:53"

#############################################
# DNS *æ— é¡»å…³æ³¨*
#############################################

dns:
  enable: true
  ipv6: false
  listen: '[::]:1053'
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true # æŸ¥è¯¢ hosts
  cache-algorithm: arc
  # å®Œå–„ Fake-IP è¿‡æ»¤ï¼šé˜²æ­¢å›½å†…æœåŠ¡å›  Fake-IP å¯¼è‡´æ— æ³•è¿æ¥æˆ–å®šä½åå·®
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
    - "geosite:cn"  # é‡ç‚¹ï¼šå›½å†…åŸŸåä¸èµ° Fake-IP
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - "+.push.apple.com"
    - "rule-set:fakeipfilter_domain"
    # ç»•è¿‡æœºåœº
    - "+.2000w.xyz"
    - "+.beijing-aliyuncs.sbs"
    # - "google.com"        # æŸäº›è°·æ­ŒæœåŠ¡éœ€è¦çœŸå® IP
    # - "+.stun.*.*"        # STUN æœåŠ¡
    # ä¸ƒå°ºå®‡çš„fake-ip-filterï¼Œéœ€è¦é…åˆè‡ªå»ºçš„è§„åˆ™
    - "rule-set:fakeipfilter_domain"
    
  fake-ip-filter-mode: blacklist
  respect-rules: true
  prefer-h3: false
  # é»˜è®¤è§£æå™¨ï¼šä»…ä½¿ç”¨å›½å†…æé€Ÿ DNSï¼Œç¡®ä¿æ‹¨å·å’ŒåŸºç¡€è¿æ¥ç§’å¼€
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  # ä»£ç†æœåŠ¡å™¨åŸŸåè§£æï¼šè§£æä½ çš„è®¢é˜…é“¾æ¥åŸŸåï¼Œå»ºè®®ç›´æ¥ç”¨å›½å†… DNS
  proxy-server-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  # direct-nameserver:
  #   - 192.168.50.1
  #   - 223.5.5.5
  # ä¸»è§£æå™¨ï¼šå¤„ç†å›½å†…åŸŸåè§£æ
  nameserver:
    - https://223.5.5.5/dns-query
    - https://119.29.29.29/dns-query
  # å¤‡ç”¨DNSï¼ˆä¸»DNSå¤±æ•ˆæ—¶å…œåº•ï¼‰
  fallback:
    - https://8.8.8.8/dns-query
    - https://1.1.1.1/dns-query
    - https://dns.google/dns-query

#############################################
# ç­–ç•¥ç»„ *éœ€é’ˆå¯¹è§„åˆ™å’Œè§„åˆ™é›†è°ƒæ•´*
#############################################

default: &default
  type: select
  proxies:
    - ç›´è¿
    - æ‰€æœ‰-æ‰‹åŠ¨
    - æ‰€æœ‰-è‡ªåŠ¨
    - é¦™æ¸¯-æ•…è½¬
    - å°æ¹¾-æ•…è½¬
    - æ–°åŠ å¡-æ•…è½¬
    - æ—¥æœ¬-æ•…è½¬
    - ç¾å›½-æ•…è½¬
    - äºšæ´²-æ•…è½¬
    - æ¬§æ´²-æ•…è½¬
    - æ‹’ç»

proxy-groups:
# ä¸šåŠ¡åˆ†æµç»„
  - {name: ğŸ¤– äººå·¥æ™ºèƒ½, <<: *default}
  - {name: ğŸ“± é€šè®¯/ç¤¾äº¤, <<: *default}
  - {name: ğŸ¢ åŠå…¬/å‚å•†, <<: *default}
  - {name: ğŸ¬ è§†é¢‘åª’ä½“, <<: *default}  
  - {name: ğŸ’» å¼€å‘/åŸºç¡€, <<: *default}


# é€‰æ‹©èŠ‚ç‚¹
  - name: æ‰€æœ‰-æ‰‹åŠ¨
    type: select
    include-all: true
    filter: "^((?!(ç›´è¿|æ‹’ç»)).)*$"

  - name: æ‰€æœ‰-è‡ªåŠ¨
    type: url-test
    include-all: true
    tolerance: 50
    interval: 300
    filter: "^((?!(ç›´è¿|æ‹’ç»)).)*$"

  # é¦™æ¸¯ç»„
  - name: "é¦™æ¸¯-æ•…è½¬"
    type: fallback
    proxies:
      - "é¦™æ¸¯-æ‰‹é€‰"
      - "é¦™æ¸¯-è‡ªåŠ¨"
    # url: http://www.gstatic.com/generate_204
    interval: 300
    lazy: false
  - name: "é¦™æ¸¯-æ‰‹é€‰"
    type: select
    include-all: true # åŒ…å«å…¨éƒ¨
    exclude-type: direct
    filter: "(?i)é¦™æ¸¯|ğŸ‡­ğŸ‡°|Hong\\s*[-_]?\\s*Kong|\\bHK\\b|HK\\d+"
  - name: "é¦™æ¸¯-è‡ªåŠ¨"
    type: url-test
    include-all: true
    exclude-type: direct
    # url: http://www.gstatic.com/generate_204
    tolerance: 50 # å®¹å·®
    interval: 300 # é—´éš”
    filter: "(?i)é¦™æ¸¯|ğŸ‡­ğŸ‡°|Hong\\s*[-_]?\\s*Kong|\\bHK\\b|HK\\d+"
    # exclude-filter: "(?i)2x|3x" # æ’é™¤2xå’Œ3x
 
    # å°æ¹¾ç»„
  - name: "å°æ¹¾-æ•…è½¬"
    type: fallback
    proxies:
      - "å°æ¹¾-æ‰‹é€‰"
      - "å°æ¹¾-è‡ªåŠ¨"
    # url: http://www.gstatic.com/generate_204
    interval: 300
    lazy: false
  - name: "å°æ¹¾-æ‰‹é€‰"
    type: select
    include-all: true # åŒ…å«å…¨éƒ¨
    exclude-type: direct
    filter: "(?i)å°æ¹¾|å°åŒ—|ğŸ‡¹ğŸ‡¼|Taiwan|\\bTW\\b|TW\\d+"
  - name: "å°æ¹¾-è‡ªåŠ¨"
    type: url-test
    include-all: true
    exclude-type: direct
    # url: http://www.gstatic.com/generate_204
    tolerance: 50 # å®¹å·®
    interval: 300 # é—´éš”
    filter: "(?i)å°æ¹¾|å°åŒ—|ğŸ‡¹ğŸ‡¼|Taiwan|\\bTW\\b|TW\\d+"

    # æ–°åŠ å¡ç»„
  - name: "æ–°åŠ å¡-æ•…è½¬"
    type: fallback
    proxies:
      - "æ–°åŠ å¡-æ‰‹é€‰"
      - "æ–°åŠ å¡-è‡ªåŠ¨"
    # url: http://www.gstatic.com/generate_204
    interval: 300
    lazy: false
  - name: "æ–°åŠ å¡-æ‰‹é€‰"
    type: select
    include-all: true # åŒ…å«å…¨éƒ¨
    exclude-type: direct
    filter: "(?i)æ–°åŠ å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|Singapore|\\bSG\\b|SG\\d+"
  - name: "æ–°åŠ å¡-è‡ªåŠ¨"
    type: url-test
    include-all: true
    exclude-type: direct
    # url: http://www.gstatic.com/generate_204
    tolerance: 50 # å®¹å·®
    interval: 300 # é—´éš”
    filter: "(?i)æ–°åŠ å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|Singapore|\\bSG\\b|SG\\d+"

    # æ—¥æœ¬ç»„
  - name: "æ—¥æœ¬-æ•…è½¬"
    type: fallback
    proxies:
      - "æ—¥æœ¬-æ‰‹é€‰"
      - "æ—¥æœ¬-è‡ªåŠ¨"
    # url: http://www.gstatic.com/generate_204
    interval: 300
    lazy: false
  - name: "æ—¥æœ¬-æ‰‹é€‰"
    type: select
    include-all: true # åŒ…å«å…¨éƒ¨
    exclude-type: direct
    filter: "(?i)æ—¥æœ¬|ä¸œäº¬|ğŸ‡¯ğŸ‡µ|Japan|\\bJP\\b|JP\\d+"
  - name: "æ—¥æœ¬-è‡ªåŠ¨"
    type: url-test
    include-all: true
    exclude-type: direct
    # url: http://www.gstatic.com/generate_204
    tolerance: 50 # å®¹å·®
    interval: 300 # é—´éš”
    filter: "(?i)æ—¥æœ¬|ä¸œäº¬|ğŸ‡¯ğŸ‡µ|Japan|\\bJP\\b|JP\\d+"

    # ç¾å›½ç»„
  - name: "ç¾å›½-æ•…è½¬"
    type: fallback
    proxies:
      - "ç¾å›½-æ‰‹é€‰"
      - "ç¾å›½-è‡ªåŠ¨"
    # url: http://www.gstatic.com/generate_204
    interval: 300
    lazy: false
  - name: "ç¾å›½-æ‰‹é€‰"
    type: select
    include-all: true # åŒ…å«å…¨éƒ¨
    exclude-type: direct
    filter: "(?i)ç¾å›½|ğŸ‡ºğŸ‡¸|United\\s*States|America|\\bUS\\b|US\\d+"
  - name: "ç¾å›½-è‡ªåŠ¨"
    type: url-test
    include-all: true
    exclude-type: direct
    # url: http://www.gstatic.com/generate_204
    tolerance: 50 # å®¹å·®
    interval: 300 # é—´éš”
    filter: "(?i)ç¾å›½|ğŸ‡ºğŸ‡¸|United\\s*States|America|\\bUS\\b|US\\d+"

    # äºšæ´²ç»„
  - name: "äºšæ´²-æ•…è½¬"
    type: fallback
    proxies:
      - "äºšæ´²-æ‰‹é€‰"
      - "äºšæ´²-è‡ªåŠ¨"
    # url: http://www.gstatic.com/generate_204
    interval: 300
    lazy: false
  - name: "äºšæ´²-æ‰‹é€‰"
    type: select
    include-all: true # åŒ…å«å…¨éƒ¨
    exclude-type: direct
    filter: "(?i)è¶Šå—|æ³°å›½|é©¬æ¥è¥¿äºš|å°åº¦|åœŸè€³å…¶|ğŸ‡»ğŸ‡³|ğŸ‡¹ğŸ‡­|ğŸ‡²ğŸ‡¾|ğŸ‡®ğŸ‡³|ğŸ‡¹ğŸ‡·|Vietnam|Thailand|Malaysia|India|Turkey|\\b(VN|TH|MY|IN|TR)\\b|(VN|TH|MY|IN|TR)\\d+"
  - name: "äºšæ´²-è‡ªåŠ¨"
    type: url-test
    include-all: true
    exclude-type: direct
    # url: http://www.gstatic.com/generate_204
    tolerance: 50 # å®¹å·®
    interval: 300 # é—´éš”
    filter: "(?i)è¶Šå—|æ³°å›½|é©¬æ¥è¥¿äºš|å°åº¦|åœŸè€³å…¶|ğŸ‡»ğŸ‡³|ğŸ‡¹ğŸ‡­|ğŸ‡²ğŸ‡¾|ğŸ‡®ğŸ‡³|ğŸ‡¹ğŸ‡·|Vietnam|Thailand|Malaysia|India|Turkey|\\b(VN|TH|MY|IN|TR)\\b|(VN|TH|MY|IN|TR)\\d+"

    # æ¬§æ´²ç»„
  - name: "æ¬§æ´²-æ•…è½¬"
    type: fallback
    proxies:
      - "æ¬§æ´²-æ‰‹é€‰"
      - "æ¬§æ´²-è‡ªåŠ¨"
    # url: http://www.gstatic.com/generate_204
    interval: 300
    lazy: false
  - name: "æ¬§æ´²-æ‰‹é€‰"
    type: select
    include-all: true # åŒ…å«å…¨éƒ¨
    exclude-type: direct
    filter: "(?i)è‹±å›½|è·å…°|æ³•å›½|å¾·å›½|ğŸ‡¬ğŸ‡§|ğŸ‡³ğŸ‡±|ğŸ‡«ğŸ‡·|ğŸ‡©ğŸ‡ª|Great\\s*Britain|Netherlands|France|Germany|\\b(GB|UK|NL|NLD|FR|DE)\\b|(GB|UK|NL|NLD|FR|DE)\\d+"
  - name: "æ¬§æ´²-è‡ªåŠ¨"
    type: url-test
    include-all: true
    exclude-type: direct
    # url: http://www.gstatic.com/generate_204
    tolerance: 50 # å®¹å·®
    interval: 300 # é—´éš”
    filter: "(?i)ç›´è¿|æ‹’ç»|è‹±å›½|è·å…°|æ³•å›½|å¾·å›½|ğŸ‡¬ğŸ‡§|ğŸ‡³ğŸ‡±|ğŸ‡«ğŸ‡·|ğŸ‡©ğŸ‡ª|Great\\s*Britain|Netherlands|France|Germany|\\b(GB|UK|NL|NLD|FR|DE)\\b|(GB|UK|NL|NLD|FR|DE)\\d+"

#############################################
# è§„åˆ™åŒ¹é… *é‡ç‚¹å…³æ³¨*
#############################################
rules:
  # - RULE-SET,TEST / Domain,Test
  # - RULE-SET,Block / Domain,Block
  # --- 01 ğŸ¤– äººå·¥æ™ºèƒ½ ---
  - RULE-SET,ai-openai,ğŸ¤– äººå·¥æ™ºèƒ½
  - RULE-SET,ai-anthropic,ğŸ¤– äººå·¥æ™ºèƒ½
  - RULE-SET,ai-gemini,ğŸ¤– äººå·¥æ™ºèƒ½
  - RULE-SET,ai-others-ip,ğŸ¤– äººå·¥æ™ºèƒ½
# --- 02 ğŸ“± é€šè®¯/ç¤¾äº¤ ---
  - RULE-SET,social-telegram,ğŸ“± é€šè®¯/ç¤¾äº¤
  - RULE-SET,social-telegram-ip,ğŸ“± é€šè®¯/ç¤¾äº¤,no-resolve
  - RULE-SET,social-twitter,ğŸ“± é€šè®¯/ç¤¾äº¤
  - RULE-SET,social-twitter-ip,ğŸ“± é€šè®¯/ç¤¾äº¤,no-resolve
  - RULE-SET,social-facebook,ğŸ“± é€šè®¯/ç¤¾äº¤
  - RULE-SET,social-facebook-ip,ğŸ“± é€šè®¯/ç¤¾äº¤,no-resolve
  - RULE-SET,social-discord,ğŸ“± é€šè®¯/ç¤¾äº¤
  # --- 03 ğŸ¢ åŠå…¬/å‚å•† ---
  - RULE-SET,office-google,ğŸ¢ åŠå…¬/å‚å•†
  - RULE-SET,office-microsoft,ğŸ¢ åŠå…¬/å‚å•†
  - RULE-SET,office-apple,ğŸ¢ åŠå…¬/å‚å•†
  # --- 04 ğŸ¬ è§†é¢‘åª’ä½“ ---
  - RULE-SET,media-youtube,ğŸ¬ è§†é¢‘åª’ä½“
  - RULE-SET,media-netflix,ğŸ¬ è§†é¢‘åª’ä½“
  - RULE-SET,media-netflix-ip,ğŸ¬ è§†é¢‘åª’ä½“,no-resolve
  - RULE-SET,media-disney,ğŸ¬ è§†é¢‘åª’ä½“
  - RULE-SET,media-tiktok,ğŸ¬ è§†é¢‘åª’ä½“
  # --- 05 ğŸ’» å¼€å‘/åŸºç¡€ ---
  - RULE-SET,dev-github,ğŸ’» å¼€å‘/åŸºç¡€
  - RULE-SET,dev-docker,ğŸ’» å¼€å‘/åŸºç¡€
  - RULE-SET,dev-python,ğŸ’» å¼€å‘/åŸºç¡€
  - RULE-SET,dev-core,ğŸ’» å¼€å‘/åŸºç¡€




#############################################
# è§„åˆ™é›† *é‡ç‚¹å…³æ³¨*
#############################################
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}

rule-providers:
  # ä¸ƒå°ºå®‡é…åˆfake-ip-filterè‡ªå»ºçš„è§„åˆ™
  fakeipfilter_domain: {<<: *domain, url: "https://raw.githubusercontent.com/wwqgtxx/clash-rules/release/fakeip-filter.mrs"}
  # TEST / Domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Check.list"}
  # Block / Domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Block.list"}  

  # --- 01 ğŸ¤– äººå·¥æ™ºèƒ½ ---
  ai-openai: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/openai.mrs"}
  ai-anthropic: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/anthropic.mrs"}
  ai-gemini: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/google-gemini.mrs"}
  ai-others-ip: {<<: *ip, url: "https://gh-proxy.com/github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/ai.mrs"}
  # 02 ğŸ“± é€šè®¯/ç¤¾äº¤
  social-telegram: {<<: *domain, url: "https://gh-proxy.com/github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/telegram.mrs"}
  social-telegram-ip: {<<: *ip, url: "https://gh-proxy.com/github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/telegram.mrs"}
  social-twitter: {<<: *domain, url: "https://gh-proxy.com/github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/twitter.mrs"}
  social-twitter-ip: {<<: *ip, url: "https://gh-proxy.com/github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/twitter.mrs"}
  social-facebook: {<<: *domain, url: "https://gh-proxy.com/github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/facebook.mrs"}
  social-facebook-ip: {<<: *ip, url: "https://gh-proxy.com/github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/facebook.mrs"}
  social-discord: {<<: *domain, url: "https://gh-proxy.com/github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/discord.mrs"}
  # 03 ğŸ¢ åŠå…¬/å‚å•†
  office-google: {<<: *domain, url: "https://gh-proxy.com/github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/google.mrs"}
  office-microsoft: {<<: *domain, url: "https://gh-proxy.com/github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/microsoft.mrs"}
  office-apple: {<<: *domain, url: "https://gh-proxy.com/github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/apple.mrs"}
  # 04 ğŸ¬ è§†é¢‘åª’ä½“
  media-youtube: {<<: *domain, url: "https://gh-proxy.com/github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/youtube.mrs"}
  media-netflix: {<<: *domain, url: "https://gh-proxy.com/github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/netflix.mrs"}
  media-netflix-ip: {<<: *ip, url: "https://gh-proxy.com/github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/netflix.mrs"}
  media-disney: {<<: *domain, url: "https://gh-proxy.com/github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/disney.mrs"}
  media-tiktok: {<<: *domain, url: "https://gh-proxy.com/github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/tiktok.mrs"}
  # 05 ğŸ’» å¼€å‘/åŸºç¡€
  dev-github: {<<: *domain, url: "https://gh-proxy.com/github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/github.mrs"}
  dev-docker: {<<: *domain, url: "https://gh-proxy.com/github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/docker.mrs"}
  dev-python: {<<: *domain, url: "https://gh-proxy.com/github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/python.mrs"}
  dev-core: {<<: *domain, url: "https://gh-proxy.com/github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-dev.mrs"}






